# Generated by Django 5.1.4 on 2025-05-09 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='year_or_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.yearsemester'),
        ),
    ]
