# Generated by Django 5.1.4 on 2025-05-10 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questionpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
