# Generated by Django 5.1.4 on 2025-05-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_registration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='year_or_semester',
            new_name='year',
        ),
    ]
