# Generated by Django 5.1.4 on 2025-05-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_year_or_semester_studymaterial_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='year',
            new_name='year_or_semester',
        ),
    ]
