# Generated by Django 5.1.4 on 2025-05-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_year_studymaterial_year_or_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='semester',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
