# Generated by Django 5.1.4 on 2025-05-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification_is_read_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='semester',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
